name: Cypress
on: [push]
jobs:
  cypress:
    name: Cypress
    runs-on: ubuntu-20.04
    env:
      MAAS_URL: http://localhost:5240
      MAAS_UI: http://localhost:8400
    steps:
      - uses: actions/checkout@main
      - name: Get branch name
        uses: nelonoel/branch-name@v1.0.1
      - name: Install MAAS
        run: |
          sudo systemctl enable snapd
          sudo snap install maas --channel=latest/edge
          sudo snap install maas-test-db --channel=latest/edge
      - name: Initialise MAAS
        run: sudo maas init region+rack --maas-url=${{env.MAAS_URL}}/MAAS --database-uri maas-test-db:///
      - name: Install Cypress
        uses: cypress-io/github-action@master
        with:
          runTests: false
      - name: Build all
        run: |
          sudo apt install yarn
          yarn build-all
      - name: Run Cypress tests without a user
        uses: cypress-io/github-action@master
        with:
          start: yarn start
          config: baseUrl=${{env.MAAS_URL}},pageLoadTimeout=100000
          install: false
          spec: "**/no-users/*.spec.ts"
          wait-on: "${{env.MAAS_UI}}/MAAS/r/machines"
          working-directory: integration
      - name: Create MAAS admin
        run: sudo maas createadmin --username=admin --password=test --email=fake@example.org
      - name: Run Cypress tests with a user
        uses: cypress-io/github-action@master
        with:
          config: baseUrl=${{env.MAAS_URL}},pageLoadTimeout=100000,ignoreTestFiles="**/no-users/*"
          install: false
          wait-on: "${{env.MAAS_UI}}/MAAS/r/machines"
          working-directory: integration
      - uses: actions/upload-artifact@v2
        if: ${{ github.ref == 'refs/heads/master' && failure() }}
        with:
          name: cypress-screenshots
          path: integration/cypress/screenshots
      - name: Create issue on failure
        if: ${{ github.ref == 'refs/heads/master' && failure() }}
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
        with:
          filename: .github/ISSUE_TEMPLATE/cypress-failure.md
          update_existing: true
