name: Cypress
on:
  push:
    branches:
      - "*"
jobs:
  cypress:
    name: Cypress
    runs-on: ubuntu-22.04
    env:
      MAAS_URL: http://localhost:5240
    steps:
      - uses: actions/checkout@main
      - name: Get branch name
        uses: nelonoel/branch-name@v1.0.1
      - name: Setup MAAS
        uses: canonical/setup-maas@main
        with:
          maas-url: ${{env.MAAS_URL}}/MAAS
      - name: Install Cypress
        uses: cypress-io/github-action@v4
        with:
          runTests: false
          install-command: yarn install
      - name: Run Cypress tests without a user
        uses: cypress-io/github-action@v4
        with:
          config: baseUrl=${{env.MAAS_URL}},pageLoadTimeout=100000
          install: false
          spec: "cypress/e2e/no-users/**/*.spec.ts"
          wait-on: "${{env.MAAS_URL}}/MAAS/r/machines"
      - name: Create MAAS admin
        run: sudo maas createadmin --username=admin --password=test --email=fake@example.org
      - name: Create MAAS non-admin user
        run: |
          export API_KEY=`sudo maas apikey --username=admin`
          maas login admin http://localhost:5240/MAAS $API_KEY
          maas admin users create username=user password=test email=fake-user@example.org is_superuser=0
      - name: Run Cypress tests with a user
        uses: cypress-io/github-action@v4
        with:
          config: baseUrl=${{env.MAAS_URL}},pageLoadTimeout=100000
          install: false
          spec: "cypress/e2e/with-users/**/*.spec.ts"
          wait-on: "${{env.MAAS_URL}}/MAAS/r/machines"
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - name: Create issue on failure
        if: failure()
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
          WORKFLOW: ${{ github.workflow }}
        with:
          filename: .github/ISSUE_TEMPLATE/ci-failure.md
          update_existing: true
